apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-app
  namespace: oficina
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: oficina-app
  template:
    metadata:
      labels:
        app: oficina-app
    spec:
      containers:
        - name: oficina-app
          image: 302789973247.dkr.ecr.sa-east-1.amazonaws.com/oficina-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: oficina-secrets
            - configMapRef:
                name: oficina-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oficina-secrets
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oficina-secrets
                  key: DB_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              cpu: "100m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
