apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
  namespace: oficina
type: Opaque
stringData:
  DB_HOST: PLACEHOLDER_DB_HOST
  DB_PORT: "5432"
  DB_NAME: oficina
  DB_USER: oficina
  DB_PASSWORD: PLACEHOLDER_DB_PASSWORD
  JWT_SECRET: PLACEHOLDER_JWT_SECRET
